---
- name: Configure hosts
  hosts: "{{ hostgroup }}"
  become: yes
  tasks:
    - debug: msg="{{ hostvars[item].ansible_host }}"
      with_items: "{{ groups[hostgroup] }}"

    - name: update host file
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      become: yes
      with_items: "{{ groups[hostgroup] }}"