---
#
- name: Install SQL-Zauberkasten
  hosts: "{{ hostgroup }}"
  become: yes
  become_user: oracle
  gather_facts: no
  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /home/oracle/opitz/SQL-Zauberkasten
        state: directory
        mode: '0755'

    - name: git clone SQL-Zauberkasten
      git:
        repo: https://github.com/Rendanic/SQL-Zauberkasten.git
        dest: /home/oracle/opitz/SQL-Zauberkasten
        version: master