---

   oracle_install_version_gi: 19.3.0.0
   oracle_asm_init_dg: data

   apply_patches_gi: True

   gi_patches:
     19.3.0.0:
        # Grid Infrastructure 18 Release Updates and Revisions Bugs Fixed Lists (Doc ID 2384954.1)
        opatch_minversion: 12.2.0.1.17
        opatchauto:
          - patchid: 29252072
            patchversion: 19.4.0.0.190716
            state: present
            path: 29708769/29708769
            subpatches:
              - 29834717
              - 29850993
              - 29851014
              - 29401763

   device_persistence: asmlib

   asm_diskgroups:        # ASM Diskgroups used for DB-storage. Should map to dict asm_storage_layout. 
    - diskgroup: data
      state: present
      properties:
        - {redundancy: external, ausize: 4}
      attributes:
        - {name: compatible.rdbms, value: 11.2.0.4.0}
        - {name: compatible.asm, value: "{{ oracle_install_version_gi }}"}
      disk:
        - {device: /dev/sdc, asmlabel: data01}
    - diskgroup: fra
      state: present
      properties:
        - {redundancy: external, ausize: 4}
      attributes:
        - {name: compatible.rdbms, value: 11.2.0.4.0}
        - {name: compatible.asm, value: "{{ oracle_install_version_gi }}"}
      disk:
        - {device: /dev/sdg, asmlabel: fra01}
