oracle_pdbs:
  - home: db193-latest
    pdb_name: orclpdb
    listener_port: 1524
    datafile_dest: /u01/oradata/
    cdb: db19
    state: present
    profiles:
      - name: DEFAULT
        state: present
        attributes:
          - { name: password_life_time, value: unlimited }
      - name: PW_UNLIMIT
        state: present
        attributes:
          - { name: password_life_time, value: "UNLIMITED" }
          - { name: password_grace_time, value: 7 }
          - { name: password_lock_time, value: 1 }
          - { name: password_verify_function, value: "null" }


    tablespaces:
         - { name: system, size: 1g, autoextend: true , next: 20M, maxsize: 3G, numfiles: 1, content: permanent, state: present }
         - { name: sysaux, size: 1g, autoextend: true , next: 20M, maxsize: 3G, numfiles: 1, content: permanent, state: present }
         - { name: temp, size: 1g, autoextend: true , next: 20M, maxsize: 3G, numfiles: 1, content: temp, state: present }
         - { name: users, size: 100M, autoextend: true , next: 100M, maxsize: 10G, numfiles: 1, content: permanent, state: present }

    init_parameters:
         - {name: db_create_file_dest, value: '/u01/oradata/', scope: both, state: present}
