apply_patches_db: True
db_homes_config:

  11204-latest:
    home: db1-latest
    version: 11.2.0.4
    oracle_home: /u01/app/oracle/product/11.2.0.4/db1-latest
    edition: EE
    opatch_minversion: 11.2.0.3.20
  #   opatchauto:
  #       - patchid: 27475913
  #         patchversion: 11.2.0.4.180417
  #         state: present
  #         subpatches:
  #             - 27338049
  #             # - 27441052
    opatch:
        # 28204707;Database Patch Set Update : 11.2.0.4.181016 (28204707)
        - patchid: 28204707
          path: 28204707/28204707
          state: present
        # 28440700;OJVM PATCH SET UPDATE 11.2.0.4.181016
        - patchid: 28440700
          path: 28440700/28440700
          state: present

db_homes_installed:
     - home: 11204-latest
       apply_patches: True
       state: present

oracle_tnsnames_config:
      testdb:
        connect:
          service_name: testdb
        address:
          - host: oradg01
          - host: oradg02

      testdb_dg1:
        connect:
          service_name: testdb1_DGMGRL
        address:
          - host: oradg01

      testdb_dg2:
        connect:
          service_name: testdb2_DGMGRL
        address:
          - host: oradg02

      testdb_test:
        tnstemplate: dgfailover2 # Custom Template for Special Data-Guard
        connect:
          service_name: test
        address:
          - host: oradg01
          - host: oradg02

tnsnames_installed:
      - home: 11204-latest
        tnsname: testdb
        state: present
      - home: 11204-latest
        tnsname: testdb_dg1
        state: present
      - home: 11204-latest
        tnsname: testdb_dg2
        state: present
      - home: 11204-latest
        tnsname: testdb_test
        state: present

sqlnet_installed:
      - home: 11204-latest
        sqlnet: sqlnetalias1
        state: present

sqlnet_config:
      sqlnetalias1:
        - {name: "ADR_BASE", value: "/u01/app/oracle/" }
        - {name: "SQLNET.ALLOWED_LOGON_VERSION_CLIENT", value: "12" }
