apply_patches_db: True
db_homes_config:

  db193-latest:
    home: db193-latest
    version: 19.3.0.0
    oracle_home: /u01/app/oracle/product/19.3/db1-latest
    imagename: db_home_19.11.zip
    edition: EE
    opatch_minversion: 12.2.0.1.19
    opatch:
      - patchid: 32545013
        patchversion: 19.11.0.0.210420
        stop_processes: True
        state: present
        path: 30869156/30869156
      - patchid: 32399816
        # Oracle JavaVM Component Release Update (OJVM RU) 19.7.0.0.200414
        patchversion: 19.11.0.0.210420
        stop_processes: True
        state: present
        path: 19.11/ojvm/32399816/

db_homes_installed:
  - home: db193-latest
    apply_patches: True
    state: present

oracle_listeners_config:
  LISTENER1524:
    home: db193-latest
    address:
      - host: "{{ansible_hostname}}"
        protocol: TCP
        port: 1521

listener_installed:
  - home: db193-latest
    listener_name: LISTENER1524
    state: present

oracle_tnsnames_config:
  dg19_orclpdb:
    connect:
      service_name: orclpdb
    address:
      - host: oradg1
      - host: oradg2

  dg19_db19dg1:
    connect:
      service_name: db19u1_DGMGRL
    address:
      - host: oradg1

  dg19_db19dg2:
    connect:
      service_name: db19u2_DGMGRL
    address:
      - host: oradg2

#sqlnet_installed:
#      - home: db193-latest
#        sqlnet: sqlnetalias1
#        state: present

sqlnet_config:
  sqlnetalias1:
    - {name: "ADR_BASE", value: "/u01/app/oracle/" }
    - {name: "SQLNET.ALLOWED_LOGON_VERSION_CLIENT", value: "12" }