apply_patches_db: True
db_homes_config:

  db1911-si-ee: &db1911-si-ee
    home: db1911-si-ee
    version: 19.3.0.0
    oracle_home: /u01/app/oracle/product/19/db1911-si-ee
    edition: EE
    opatch_minversion: 12.2.0.1.19
    opatch:
      - patchid: 32545013
        patchversion: 19.11.0.0.210420
        stop_processes: True
        state: present
        path: 30869156/30869156
      - patchid: 32399816
        # Oracle JavaVM Component Release Update (OJVM RU) 19.7.0.0.200414
        patchversion: 19.11.0.0.210420
        stop_processes: True
        state: present
        path: 19.11/ojvm/32399816/

  db1814-si-ee: &db1814-si-ee
    home: db1814-si-ee
    version: 18.3.0.0
    oracle_home: /u01/app/oracle/product/18/db1814-si-ee
    edition: EE
    opatch_minversion: 12.2.0.1.19
    opatch:
      - # JOB PROCESSES FILL THE FILESYSTEM WITH TRACE FILES AFTER INSTALLING BUG 29541742
        { patchid: 30352715, state: absent, excludeUPI: 24122032, stop_processes: True }
      - patchid: 32204699
        patchversion: 18.14.0.0.210420
        stop_processes: True
        state: present
        path: 18.14/dbru/32524155
      # Opatch conflict check fail with - Please rebuild the superset patch xxx to make sure it supersedes all the relevant patch [xxx , xxx] (Doc ID 2477824.1)
      # - patchid: 30352715
      #   # Oracle JavaVM Component Release Update (OJVM RU) 19.7.0.0.200414
      #   stop_processes: True
      #   state: present
      #   path: 18.14/p30352715_1814000DBRU_Linux-x86-64.zip
      - # JOB PROCESSES FILL THE FILESYSTEM WITH TRACE FILES AFTER INSTALLING BUG 29541742
        { patchid: 30352715, state: present, stop_processes: True, path: 18.14/p30352715_1814000DBRU_Linux-x86-64.zip}

  db1813-si-ee: &db1813-si-ee
    home: db1813-si-ee
    version: 18.3.0.0
    oracle_home: /u01/app/oracle/product/18/db1813-si-ee
    edition: EE
    opatch_minversion: 12.2.0.1.19
    opatch:
      - patchid: 32204699
        patchversion: 18.13.0.0.210119
        stop_processes: True
        state: present
        path: 18.13/dbru/32204699
      - patchid: 30352715
        # Oracle JavaVM Component Release Update (OJVM RU) 19.7.0.0.200414
        patchversion: 18.13.0.0.210119
        stop_processes: True
        state: present
        path: 18.13/p30352715_1813000DBRU_Linux-x86-64.zip
      - # JOB PROCESSES FILL THE FILESYSTEM WITH TRACE FILES AFTER INSTALLING BUG 29541742
        { patchid: 30352715, state: present, stop_processes: True, path: 18.13/p30352715_1813000DBRU_Linux-x86-64.zip}

  db12201-si-ee:
    home: db12201-si-ee
    version: 12.2.0.1
    oracle_home: /u01/app/oracle/product/12.2.0.1/db12201-si-ee
    edition: EE
    dnfs: true
    opatch_minversion: 12.2.0.1.13

  db12102-si-ee:
    home: db12102-si-ee
    version: 12.1.0.2
    oracle_home: /u01/app/oracle/product/12.1.0.2/db12102-si-ee
    edition: EE
    dnfs: true
    opatch_minversion: 12.2.0.1.13

  db11204-si-ee:
    home: db11204-si-ee
    version: 11.2.0.4
    oracle_home: /u01/app/oracle/product/11.2.0.4/db11204-si-ee
    edition: EE
    opatch_minversion: 11.2.0.3.20

  # Current Mapping of ORACLE_HOMEs
  # use this mapping for fast change between the Release Updates
  # <<: * => merge values from alias and overwrite oracle_home + home
  db19-si-ee:
    << : *db1911-si-ee
    imagename: db_home_19.11.zip
    oracle_home: /u01/app/oracle/product/19/db1
    home: db19-si-ee
  db18-si-ee:
    << : *db1813-si-ee
    oracle_home: /u01/app/oracle/product/18/db1
    home: db18-si-ee

db_homes_installed:
  # - home: db19-si-ee
  #   apply_patches: True
  #   state: present
  - home: db18-si-ee
    apply_patches: True
    state: present
