  configure_public_yum_repo: False
  configure_motd: False

  configure_cluster: False
  role_separation: False
  configure_oracle_sudo: True
  oracle_user: oracle
  disable_EE_options: True
  autostartup_service: true

  configure_hugepages_by: memory
  size_in_gb_hugepages: 0

  oracle_stage: /u01/stage

  configure_host_disks: True

  host_fs_layout:
    - vgname: vgora
      state: present
      filesystem:
        - {mntp: /u01, lvname: lvora, lvsize: 100%FREE, fstype: ext4}
      disk:
        - {device: /dev/sdb, pvname: /dev/sdb1}
    - vgname: vgoradata
      state: present
      filesystem:
        - {mntp: /u02, lvname: lvoradata, lvsize: 100%FREE, fstype: xfs, fsopts: "-m reflink=1 -m crc=1"}
      disk:
        - {device: /dev/sdc, pvname: /dev/sdc1}