---
  is_sw_source_local: true
  oracle_sw_copy: False
  oracle_sw_unpack: False

  oracle_stage_remote: /sw/oracle/linux64
  
  s3_bucket: octbr-ansible-oracle-images
  s3_bucket_region: eu-central-1
  s3_bucket_subdir: /oracle
  s3_iam_role: ansible-oracleansible-oracle_SSMRoleForInstances