oracle_pdbs:
  - home: 12201-latest
    pdb_name: orclpdb
    listener_port: 1522
    datafile_dest: /u02/oradata/
    cdb: testdb
    state: present
    tablespaces:
         - { name: system, size: 1g, autoextend: true , next: 20M, maxsize: 3G, numfiles: 1, content: permanent, state: present }
         - { name: sysaux, size: 1g, autoextend: true , next: 20M, maxsize: 3G, numfiles: 1, content: permanent, state: present }
         - { name: temp, size: 1g, autoextend: true , next: 20M, maxsize: 3G, numfiles: 1, content: temp, state: present }

    init_parameters:
         - {name: db_create_file_dest, value: '/u02/oradata/', scope: both, state: present}
#    services:
#           - { name: app1_service,  state: started }
#    users:
#      - schema: appuser1
#        default_tablespace: appuser1_data
#        grants:
#           - approle1
#        state: present
#    roles:
#      - name: approle1
#        grants:
#             - create session
#             - create table
#             - select any table
#             - select any dictionary
#        state: present
