# DB
default_dbpass: Oracle123
dbpasswords:
      testdb:
        system: Oracle_123
        sys: Oracle_123
        dbsnmp: dbsnmp
        c##check_mk: monitoring
        pdbadmin: Oracle_123
        orclpdb1:
           appuser1: appuser1