oracle_pdbs:
  - home: 12102-latest
    pdb_name: orclpdb
    listener_port: 1522
    datafile_dest: /u02/oradata/
    cdb: testdb
    state: present
    profiles:
      - name: DEFAULT
        state: present
        attributes:
          - { name: password_life_time, value: unlimited }
      - name: PW_UNLIMIT
        state: present
        attributes:
          - { name: password_life_time, value: "UNLIMITED" }
          - { name: password_grace_time, value: 7 }
          - { name: password_lock_time, value: 1 }
          - { name: password_verify_function, value: "null" }


    tablespaces:
         - { name: system, size: 1g, autoextend: true , next: 20M, maxsize: 3G, numfiles: 1, content: permanent, state: present }
         - { name: sysaux, size: 1g, autoextend: true , next: 20M, maxsize: 3G, numfiles: 1, content: permanent, state: present }
         - { name: temp, size: 1g, autoextend: true , next: 20M, maxsize: 3G, numfiles: 1, content: temp, state: present }

    init_parameters:
         - {name: db_create_file_dest, value: '/u02/oradata/', scope: both, state: present}
#    services:
#           - { name: app1_service,  state: started }
#    users:
#      - schema: appuser1
#        default_tablespace: appuser1_data
#        grants:
#           - approle1
#        state: present
#    roles:
#      - name: approle1
#        grants:
#             - create session
#             - create table
#             - select any table
#             - select any dictionary
#        state: present
  - home: 12201-latest
    pdb_name: orclpdb
    listener_port: 1523
    datafile_dest: /u02/oradata/
    cdb: t122
    state: present
    profiles:
      - name: DEFAULT
        state: present
        attributes:
          - { name: password_life_time, value: unlimited }
      - name: PW_UNLIMIT
        state: present
        attributes:
          - { name: password_life_time, value: "UNLIMITED" }
          - { name: password_grace_time, value: 7 }
          - { name: password_lock_time, value: 1 }
          - { name: password_verify_function, value: "null" }


    tablespaces:
         - { name: system, size: 1g, autoextend: true , next: 20M, maxsize: 3G, numfiles: 1, content: permanent, state: present }
         - { name: sysaux, size: 1g, autoextend: true , next: 20M, maxsize: 3G, numfiles: 1, content: permanent, state: present }
         - { name: temp, size: 1g, autoextend: true , next: 20M, maxsize: 3G, numfiles: 1, content: temp, state: present }

    init_parameters:
         - {name: db_create_file_dest, value: '/u02/oradata/', scope: both, state: present}
#    services:
#           - { name: app1_service,  state: started }
#    users:
#      - schema: appuser1
#        default_tablespace: appuser1_data
#        grants:
#           - approle1
#        state: present
#    roles:
#      - name: approle1
#        grants:
#             - create session
#             - create table
#             - select any table
#             - select any dictionary
#        state: present
