plugin: aws_ec2

regions:
  - eu-central-1

strict: False

filters:
  instance-state-name: running

hostnames:
  - ip-address
  - dns-name
  - tag:Name
  - private-ip-address

keyed_groups:
  - key: tags
    prefix: tag