
oracle_listeners_config:
   LISTENER1524:
        home: db193-latest
        address:
          - host: "{{ansible_hostname}}"
            protocol: TCP
            port: 1524

listener_installed:
      - home: db193-latest
        listener_name: LISTENER1524
        state: present

