
oracle_listeners_config:
   LISTENER1522:
        home: 12201-latest
        address:
          - host: "{{ansible_hostname}}"
            protocol: TCP
            port: 1522

listener_installed:
      - home: 12201-latest
        listener_name: LISTENER1522
        state: present
