all:
  children:
    dbfs:
      children:
        # hostgroup for Data-Guard 19c setup
        ###################################################################
        # WARNING! DataGuard Setuup is not completed in ansible-oracle!!! #
        ###################################################################

        dg19:
          hosts:
            oradg1:
              ansible_host: 192.168.56.181
            oradg2:
              ansible_host: 192.168.56.182
