apply_patches_db: True

db_homes_config:
  12201-latest:
    home: db1-latest
    version: 12.2.0.1
    oracle_home: /u01/app/oracle/product/12.2.0.1/db1-latest
    edition: EE
    opatch_minversion: 12.2.0.1.14

    opatchauto:
        - patchid: 29252072
          patchversion: 12.2.0.1.190416
          path: 29252072/29252072/29301687
          state: present
          subpatches:
              - 29314339
              - 29314339

#        - patchid: 28183653
#          patchversion: 12.2.0.1.180717
#          state: present
#          subpatches:
#              - 28163133
#              - 28163190
#        - patchid: 27468969
#          patchversion: 12.2.0.1.180417
#          state: present
#          subpatches:
#              - 27674384
#              - 27464465

    opatch:
        - patchid: 29249637
          patchversion: 12.2.0.1.190416
          path: 29252072/29252072/29249637
          state: present

db_homes_installed:
     - home: 12201-latest
       apply_patches: True
       state: present

oracle_tnsnames_config:
      testdb:
        connect:
          service_name: testdb
        address:
          - host: oradb04
            protocol: TCP
            port: 1521

      testdb1_dgmgrl:
        connect:
          service_name: testdbu1_DGMGRL
        address:
          - host: oradb04
            protocol: TCP
            port: 1521

      testdb_rw:
        tnstemplate: dgfailover2 # Custom Template for Special Data-Guard
        connect:
          service_name: test
        address:
          - host: oradb04

tnsnames_installed:
      - home: 12201-latest
        tnsname: testdb
        state: present
      - home: 12201-latest
        tnsname: testdb1_dgmgrl
        state: present
      - home: 12201-latest
        tnsname: testdb_rw
        state: present

sqlnet_installed:
      - home: 12201-latest    
        sqlnet: sqlnetalias1
        state: present

sqlnet_config:
      sqlnetalias1:
        - {name: "ADR_BASE", value: "/u01/app/oracle/" }
        - {name: "SQLNET.ALLOWED_LOGON_VERSION_CLIENT", value: "12" }
