
oracle_listeners_config:
   LISTENER:
        home: db19-si-ee
        address:
          - host: "{{ansible_hostname}}"
            protocol: TCP
            port: 1521

listener_installed:
      - home: db19-si-ee
        listener_name: LISTENER
        state: present