tnsnames_installed:
  - home: db193-latest
    tnsname: dg19_orclpdb
    state: present
  - home: db193-latest
    tnsname: dg19_db19dg1
    state: present
  - home: db193-latest
    tnsname: dg19_db19dg2
    state: present