oracle_listeners_config:
  LISTENER:
    home: db19-latest-oa
    address:
      - host: "{{ansible_hostname}}"
        protocol: TCP
        port: 1521

listener_installed:
  - home: db19-latest-oa
    listener_name: LISTENER
    state: present