---

   oracle_install_version_gi: 19.3.0.0
   oracle_install_image_gi: grid_home_19.11.zip

   oracle_asm_init_dg: data

   apply_patches_gi: True

   gi_patches:
     19.3.0.0:
        opatch_minversion: 12.2.0.1.23
        imagename: grid_home_19.11.zip
        opatchauto:
          - patchid: 32545008
            patchversion: 19.11.0.0.210420
            state: present
            path: 19.11/gi/32545008
            subpatches:
              - 32579761
              - 32545013
              - 32576499
              - 32585572
              - 32584670

   device_persistence: asmlib

   asm_diskgroups:        # ASM Diskgroups used for DB-storage. Should map to dict asm_storage_layout. 
    - diskgroup: data
      state: present
      properties:
        - {redundancy: external, ausize: 4}
      attributes:
        - {name: compatible.rdbms, value: 11.2.0.4.0}
        - {name: compatible.asm, value: "{{ oracle_install_version_gi }}"}
      disk:
        - {device: /dev/sdc, asmlabel: data01}
    - diskgroup: fra
      state: present
      properties:
        - {redundancy: external, ausize: 4}
      attributes:
        - {name: compatible.rdbms, value: 11.2.0.4.0}
        - {name: compatible.asm, value: "{{ oracle_install_version_gi }}"}
      disk:
        - {device: /dev/sdg, asmlabel: fra01}