db_homes_config:
  db19-latest-oa: # oa => opatchauto
    home: db193-latest
    version: 19.3.0.0
    oracle_home: /u01/app/oracle/product/19/db1-latest
    edition: EE
    opatch_minversion: 12.2.0.1.19
    opatchauto:
      - patchid: 30899722
        patchversion: 19.7.0.0.200414
        state: present
        path: 30899722/30899722
        subpatches:
          - 30869156
