---
  configure_public_yum_repo: False
  configure_motd: False

  configure_cluster: False
  role_separation: False
  configure_oracle_sudo: True
  oracle_user: oracle
  disable_EE_options: True

  configure_hugepages_by: memory
  size_in_gb_hugepages: 0

  oracle_stage: /u01/stage
  autostartup_service: true

  configure_host_disks: true

  host_fs_layout:
   - vgname: rootvg
     state: present
     filesystem:
       - {mntp: /u01, lvname: lvora, lvsize: 15g, fstype: ext4}
       - {mntp: /u02, lvname: lvoradata, lvsize: 25g, fstype: ext4}
     disk:
       - {device: /dev/sda, pvname: /dev/sda2}